# Generated by Django 4.2.5 on 2023-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_alter_signup_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='fast_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='initial_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='rsi_overbought',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='rsi_oversold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='rsi_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='slow_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='stop_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
