# Generated by Django 4.2.5 on 2023-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_signup_end_date_signup_fast_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='strategy',
            field=models.CharField(choices=[('GC', 'Golden Cross'), ('ATR', 'ATR'), ('rsi', 'RSI'), ('bollingerbands', 'Bollingerbands'), ('smacross', 'SmaCross')], default='Smacross', max_length=100),
        ),
    ]
