# Generated by Django 4.2.5 on 2023-11-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0004_alter_signup_stop_loss_alter_signup_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='ticker',
            new_name='Ticker',
        ),
    ]
