# Generated by Django 4.2.5 on 2023-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0005_rename_ticker_signup_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='strategy',
            field=models.CharField(choices=[('GC', 'GoldenCross'), ('ATR', 'ATR'), ('RSI', 'RSI'), ('BB', 'Bollingerbands'), ('SC', 'SmaCross')], default='GC', max_length=100),
        ),
    ]
