# Generated by Django 4.2.5 on 2023-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0006_alter_signup_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='strategy',
            field=models.CharField(choices=[('GC', 'GoldenCross'), ('ATR', 'ATR'), ('RSI', 'RSI'), ('BB', 'Bollingerbands'), ('SMA', 'Sma')], default='GC', max_length=100),
        ),
    ]
