# Generated by Django 4.2.5 on 2023-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0007_alter_signup_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='devfactor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
