# Generated by Django 4.2.5 on 2023-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0008_signup_devfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
